[package]
name = "gain"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baseplug = { git = "https://github.com/wrl/baseplug.git", branch="trunk" }
iced_baseview = { git = "https://github.com/BillyDM/iced_baseview", branch="master", features=["canvas"] }
# iced_baseview = { path = "../../iced_baseview", features=["canvas"] }
iced_audio = { git = "https://github.com/BillyDM/iced_audio", branch="iced_git" }
serde = { version = "1.0", features = ["derive"] }
raw-window-handle = "0.3"
vst = "0.2"